name: ArenaSD
version: '${version}'
main: com.saratoga.arenaSD.ArenaSD
api-version: '1.21'
description: Search and Destroy (Bomb) game mode for BattleArena
author: Saratoga
depend:
  - BattleArena
commands:
  snd:
    description: Search and Destroy game mode commands
    aliases: [searchanddestroy, bomb]
